/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useMemo, useState } from "react";
type Mode="PET"|"PLASTIC";
type Vendor={id:number;name:string;phone?:string;location?:string;notes?:string};
export default function VendorManagement({data,mode,post}:{data:any;mode:Mode;post:(action:string,body:any)=>Promise<boolean>}) {
  const vendors=useMemo(()=>((data?.suppliers||[]) as Vendor[]),[data?.suppliers]);
  const purchases=(data?.purchases||[]).filter((p:any)=>p.mode===mode);
  const payments=(data?.vendorPayments||[]).filter((p:any)=>p.mode===mode);
  const summary=(data?.vendorSummary||[]).filter((v:any)=>v.mode===mode);
  const [selected,setSelected]=useState<number|null>(null);
  const [form,setForm]=useState({name:"",location:"",phone:"",notes:""});
  const [showAdd,setShowAdd]=useState(false);
  const [editing,setEditing]=useState(false);
  const [advance,setAdvance]=useState({amount:"",notes:""});
  const [payment,setPayment]=useState({amount:"",paymentMode:"Cash",notes:""});
  const vendor=vendors.find(v=>v.id===selected);
  const vs=summary.filter((v:any)=>v.id===selected);
  const vp=purchases.filter((p:any)=>p.supplier_id===selected);
  const ledger=payments.filter((p:any)=>p.supplier_id===selected);
  const totals=useMemo(()=>({kg:vp.reduce((n:any,p:any)=>n+Number(p.quantity_kg||0),0),value:vp.reduce((n:any,p:any)=>n+Number(p.total_amount||0),0),paid:vp.reduce((n:any,p:any)=>n+Number(p.paid_amount||0),0),out:vp.reduce((n:any,p:any)=>n+Number(p.credit_amount||0),0),advance:vs.reduce((n:any,v:any)=>n+Number(v.advance||0),0)}),[vp,vs]);
  const vendorRows=useMemo(()=>vendors.map(v=>{const rows=purchases.filter((p:any)=>p.supplier_id===v.id);const sums=summary.filter((s:any)=>s.id===v.id);return {vendor:v,purchases:rows,kg:rows.reduce((n:number,p:any)=>n+Number(p.quantity_kg||0),0),value:rows.reduce((n:number,p:any)=>n+Number(p.total_amount||0),0),paid:rows.reduce((n:number,p:any)=>n+Number(p.paid_amount||0),0),outstanding:rows.reduce((n:number,p:any)=>n+Number(p.credit_amount||0),0),advance:sums.reduce((n:number,s:any)=>n+Number(s.advance||0),0),materials:Array.from(new Set(rows.map((p:any)=>p.material_name).filter(Boolean))).join(", ")}}),[vendors,purchases,summary]);
  const overall=useMemo(()=>vendorRows.reduce((a,v)=>({kg:a.kg+v.kg,value:a.value+v.value,paid:a.paid+v.paid,outstanding:a.outstanding+v.outstanding,advance:a.advance+v.advance}),{kg:0,value:0,paid:0,outstanding:0,advance:0}),[vendorRows]);
  async function addVendor(){if(await post("addSupplier",form)){setForm({name:"",location:"",phone:"",notes:""});setShowAdd(false);}}
  async function editVendor(){if(vendor&&await post("updateSupplier",{supplierId:vendor.id,...form}))setEditing(false);}
  async function addAdvance(){if(vendor&&await post("addVendorAdvance",{mode,supplierId:vendor.id,amount:Number(advance.amount),notes:advance.notes}))setAdvance({amount:"",notes:""});}
  async function makePayment(){if(vendor&&await post("payVendor",{mode,supplierId:vendor.id,amount:Number(payment.amount),paymentMode:payment.paymentMode,notes:payment.notes}))setPayment({amount:"",paymentMode:"Cash",notes:""});}
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3">
      <div><h2 className="text-lg font-bold">Vendor Overview</h2><p className="ad-muted text-sm">All vendors, material supplied, payments, outstanding and advances.</p></div>
      <button className="ad-btn ad-btn-primary" onClick={()=>setShowAdd(true)}>+ Add Vendor</button>
    </div>
    {showAdd&&<div className="ad-card p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">Add New Vendor</h3><button className="ad-btn ad-btn-ghost" onClick={()=>setShowAdd(false)}>Close</button></div><div className="grid gap-2 md:grid-cols-4"><input className="ad-input" placeholder="Vendor name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="ad-input" placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><input className="ad-input" placeholder="Contact number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="ad-input" placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="mt-3 flex gap-2"><button className="ad-btn ad-btn-primary" onClick={addVendor}>Save Vendor</button><button className="ad-btn ad-btn-ghost" onClick={()=>setShowAdd(false)}>Cancel</button></div></div>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="ad-card p-4"><span className="ad-muted text-xs">Total Vendors</span><b className="mt-1 block text-xl">{vendors.length}</b></div><div className="ad-card p-4"><span className="ad-muted text-xs">Material Supplied</span><b className="mt-1 block text-xl">{overall.kg.toFixed(2)} kg</b></div><div className="ad-card p-4"><span className="ad-muted text-xs">Purchase Value</span><b className="mt-1 block text-xl">₹{overall.value.toFixed(2)}</b></div><div className="ad-card p-4"><span className="ad-muted text-xs">Outstanding</span><b className="mt-1 block text-xl">₹{overall.outstanding.toFixed(2)}</b></div><div className="ad-card p-4"><span className="ad-muted text-xs">Advance Balance</span><b className="mt-1 block text-xl">₹{overall.advance.toFixed(2)}</b></div></div>
    <div className="ad-card p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">All Vendors</h3><span className="ad-muted text-xs">{mode}</span></div>{vendors.length===0?<div className="py-8 text-center ad-muted">No vendors added yet.</div>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{vendorRows.map(v=><div key={v.vendor.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-2"><div><b className="text-base">{v.vendor.name}</b><p className="ad-muted text-xs">{v.vendor.location||"Location not added"}{v.vendor.phone?" · "+v.vendor.phone:""}</p></div><span className="rounded-full px-2 py-1 text-[10px] font-semibold">{v.purchases.length} purchases</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div><span className="ad-muted">Materials</span><b className="block truncate">{v.materials||"—"}</b></div><div><span className="ad-muted">Weight</span><b className="block">{v.kg.toFixed(2)} kg</b></div><div><span className="ad-muted">Paid</span><b className="block">₹{v.paid.toFixed(2)}</b></div><div><span className="ad-muted">Outstanding</span><b className="block">₹{v.outstanding.toFixed(2)}</b></div><div><span className="ad-muted">Advance</span><b className="block">₹{v.advance.toFixed(2)}</b></div><div><span className="ad-muted">Purchase Value</span><b className="block">₹{v.value.toFixed(2)}</b></div></div><button className="ad-btn ad-btn-primary mt-4 w-full" onClick={()=>setSelected(v.vendor.id)}>View History</button></div>)}</div>}</div>
    {vendor?<div className="space-y-4"><div className="ad-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{vendor.name}</h2><p className="ad-muted text-sm">{vendor.location||"Location not added"} · {vendor.phone||"No contact number"}</p></div><div className="flex gap-2"><button className="ad-btn ad-btn-ghost" onClick={()=>{setForm({name:vendor.name,location:vendor.location||"",phone:vendor.phone||"",notes:vendor.notes||""});setEditing(true)}}>Edit</button><button className="ad-btn ad-btn-ghost" onClick={()=>setSelected(null)}>Close</button></div></div>{editing&&<div className="mt-4 grid gap-2 md:grid-cols-4"><input className="ad-input" placeholder="Vendor name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="ad-input" placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><input className="ad-input" placeholder="Contact number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="ad-input" placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><div className="md:col-span-4 flex gap-2"><button className="ad-btn ad-btn-primary" onClick={editVendor}>Save Changes</button><button className="ad-btn ad-btn-ghost" onClick={()=>setEditing(false)}>Cancel</button></div></div>}<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div><span className="ad-muted text-xs">Purchases</span><b className="block">{vp.length}</b></div><div><span className="ad-muted text-xs">Total weight</span><b className="block">{totals.kg.toFixed(2)} kg</b></div><div><span className="ad-muted text-xs">Purchase value</span><b className="block">₹{totals.value.toFixed(2)}</b></div><div><span className="ad-muted text-xs">Total paid</span><b className="block">₹{totals.paid.toFixed(2)}</b></div><div><span className="ad-muted text-xs">Outstanding / Advance</span><b className="block">₹{totals.out.toFixed(2)} / ₹{totals.advance.toFixed(2)}</b></div></div></div>
    <div className="grid gap-4 md:grid-cols-2"><div className="ad-card p-4"><h3 className="mb-3 font-semibold">Give Vendor Advance</h3><input className="ad-input mb-2 w-full" type="number" placeholder="Advance amount" value={advance.amount} onChange={e=>setAdvance({...advance,amount:e.target.value})}/><input className="ad-input mb-2 w-full" placeholder="Notes" value={advance.notes} onChange={e=>setAdvance({...advance,notes:e.target.value})}/><button className="ad-btn ad-btn-primary" onClick={addAdvance}>Save Advance</button></div><div className="ad-card p-4"><h3 className="mb-3 font-semibold">Make Payment</h3><input className="ad-input mb-2 w-full" type="number" placeholder="Payment amount" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/><select className="ad-input mb-2 w-full" value={payment.paymentMode} onChange={e=>setPayment({...payment,paymentMode:e.target.value})}><option>Cash</option><option>UPI</option><option>Bank Transfer</option><option>Cheque</option></select><input className="ad-input mb-2 w-full" placeholder="Notes" value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})}/><button className="ad-btn ad-btn-primary" onClick={makePayment}>Record Payment</button></div></div>
    <div className="ad-card p-4"><h3 className="mb-3 font-semibold">Material & Purchase History</h3><div className="ad-table-wrap"><table className="ad-table"><thead><tr><th>Date</th><th>Material</th><th>Qty</th><th>Rate</th><th>Total</th><th>Paid</th><th>Outstanding</th></tr></thead><tbody>{vp.map((p:any)=><tr key={p.id}><td>{p.purchase_date}</td><td>{p.material_name}</td><td>{p.quantity_kg} kg</td><td>₹{p.rate_per_kg}</td><td>₹{p.total_amount}</td><td>₹{p.paid_amount}</td><td>₹{p.credit_amount}</td></tr>)}</tbody></table></div></div>
    <div className="ad-card p-4"><h3 className="mb-3 font-semibold">Payment / Transaction History</h3><div className="ad-table-wrap"><table className="ad-table"><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Mode</th><th>Material</th><th>Notes</th></tr></thead><tbody>{ledger.map((p:any)=><tr key={p.id}><td>{p.payment_date}</td><td>{p.payment_type}</td><td>₹{p.amount}</td><td>{p.payment_mode}</td><td>{p.materialName||"—"}</td><td>{p.notes||"—"}</td></tr>)}</tbody></table></div></div>
    </div>:<div className="ad-card p-5 ad-muted">Click “View History” on any vendor to open its complete details.</div>}
  </div>;
}
